### ISSUE TITLE
Plugin is panicing if trying to lookup secret that does not exist

### ISSUE THREAD

**Issue by mdanielolsson** [Bisnode/kubectl-tbac#6]
```
$ kubectl tbac get secret no-existing-secret
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/Bisnode/kubectl-tbac/cmd.GetSecretDescription(0x138fce0, 0xc000263a40, 0x7ffcf42617a0, 0x12, 0xc00027cb40, 0xc00033b7d0, 0x5)
	/home/runner/work/kubectl-tbac/kubectl-tbac/cmd/get_secret.go:122 +0x708
github.com/Bisnode/kubectl-tbac/cmd.glob..func3(0x1b44ac0, 0xc000299a50, 0x1, 0x1)
	/home/runner/work/kubectl-tbac/kubectl-tbac/cmd/get_secret.go:54 +0x2bb
github.com/spf13/cobra.(*Command).execute(0x1b44ac0, 0xc000299a10, 0x1, 0x1, 0x1b44ac0, 0xc000299a10)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1b43860, 0x4076ef, 0xc0000520b8, 0x0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/Bisnode/kubectl-tbac/cmd.Execute()
	/home/runner/work/kubectl-tbac/kubectl-tbac/cmd/root.go:55 +0x2d
main.main()
	/home/runner/work/kubectl-tbac/kubectl-tbac/main.go:21 +0x20

```

**Comment by mdanielolsson** [comment]
Fixed in v1.0.0
